services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "default_pwd"
    volumes:
      - ./src/migrations:/migrations
      - ./migrations.sh:/docker-entrypoint-initdb.d/migrations.sh
  proxy:
    image: envoyproxy/envoy-dev:582ae02170b4c0254d5b1b32172657bf961835a1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8086:8086"
  # opentelemetry:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14250:14250"
  #     - "14268:14268"
  #     - "14269:14269"
  #     - "9411:9411"
  #     - "4317:4317"
  #     - "4318:4318"